import "@/styles/globals.css";
import Sidebar from "../components/Sidebar";

export const metadata = {
  title: "Amazon Web Scraper",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex bg-[#F7FBFF] h-screen overflow-y-auto ">
        <Sidebar />

        <main className="p-10 max-w-7xl mx-auto w-full">{children}</main>
      </body>
    </html>
  );
}
